DROP DATABASE IF EXISTS posse;
CREATE DATABASE posse;
USE posse;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE diary (
    id INT AUTO_INCREMENT PRIMARY KEY,
    content TEXT,
    learned TEXT,
    concern TEXT,
    kind TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE advice (
    id INT AUTO_INCREMENT PRIMARY KEY,
    advice_text TEXT
);

CREATE TABLE todos(
    id INT AUTO_INCREMENT PRIMARY KEY,
    task VARCHAR(255) NOT NULL,
    is_completed BOOLEAN DEFAULT FALSE
);